apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 8Gi

