---
# user-auth-api-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: user-auth-api
spec:
  selector:
    app: user-auth-api
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
