apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
type: Opaque
data:
  username: ZWxhc3RpYw==         # elastic (base64 인코딩 결과)
  password: ZWxhc3RpY3N0YWNr    # elasticstack (base64 인코딩 결과)
