apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: chat-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

